# Generated by Django 4.1.1 on 2022-09-16 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("ticker", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Selected", "No Def"),
                            ("Layer 1", "Layer 1"),
                            ("Layer 2", "Layer 2"),
                            ("DeFi", "Defi"),
                            ("Bridge", "Bridge"),
                        ],
                        default="Not Selected",
                        max_length=30,
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("project_url", models.URLField(blank=True, default=None)),
                ("market_cap", models.IntegerField()),
                ("last_price", models.FloatField()),
                ("notes", models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
