# Generated by Django 4.1.1 on 2022-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchain",
            name="last_price",
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="blockchain",
            name="market_cap",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blockchain",
            name="project_url",
            field=models.URLField(default=None),
        ),
    ]
