# Generated by Django 4.1.1 on 2022-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0002_alter_blockchain_last_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchain",
            name="project_url",
            field=models.URLField(blank=True),
        ),
    ]
