# Generated by Django 4.1.1 on 2022-09-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0003_alter_blockchain_project_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockchain",
            old_name="status",
            new_name="type",
        ),
    ]
