# Generated by Django 4.1.1 on 2022-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0004_rename_status_blockchain_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchain",
            name="notes",
            field=models.CharField(default="", max_length=200),
        ),
    ]
