#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - step:
        name: Django API Test
        caches:
          - pip
        script:
          - pip install pipenv --upgrade
          - pipenv install --system
          - export PYTHONPATH=$PYTHONPATH:$PYTHONPATH/api/pytest_refresh
          - pytest api/pytest_refresh -vs --durations=0 --junitxml=test-reports/report.xml
